### ISSUE TITLE
Unknown host for SRV record

### ISSUE THREAD

**Issue by KisenaMiyuki** [barbarbar338/ncfs#11]
I've gone through the same process myself before I stumbled upon this repo, but I couldn't get the SRV name (mc.example.com) to resolve, no matter how many times I flush the dns cache.
I'm sure I have the CNAME record to point to the ngrok random url, and the SRV record to have the correct format in name field (_minecraft._tcp.mc.example.com) and the port number to be correct.

Also I noticed the last echo message in ncfs.sh outputs the ngrok random url but no the SRV name, is that because the SRV way is indeed not viable?

**Comment by KisenaMiyuki** [comment]
Nevermind, I tried to ping mc.example.com without success, but for some reason minecraft recognize that.

**Comment by barbarbar338** [comment]
> Also I noticed the last echo message in ncfs.sh outputs the ngrok random url but no the SRV name, is that because the SRV way is indeed not viable?

I intentionally echoed the ngrok url because we already know what dns records we used but don't know the randomly generated ngrok url :))
