### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by JamesDAdams** [barbarbar338/ncfs#3]
That would be greate to have a docker image with ngrock and ths script

**Comment by barbarbar338** [comment]
Great idea! If you want you can create a PR for it :)

**Comment by HidemaruOwO** [comment]
I will work on the Docker version once this PR is merged!
#4

**Comment by barbarbar338** [comment]
> I will work on the Docker version once this PR is merged! #4

Done!

**Comment by HidemaruOwO** [comment]
Thank you!!
I will work it.

**Comment by barbarbar338** [comment]
Docker support added with #5 thanks to @HidemaruOwO!
